"EASY":-

(1) How many total bookings are in the system?

SELECT COUNT(*) AS total_bookings	
FROM airline_ticket_bookings

(2) Retrieve all bookings made by female customers.

SELECT * FROM airline_ticket_bookings
WHERE gender = 'Female' 

(3) Display all bookings made via the website.

SELECT * FROM airline_ticket_bookings
WHERE booking_source = 'Website'

"MODERATE":-

(4) Calculate the total revenue generated from all confirmed bookings.

SELECT SUM(price) AS Total_Revenue
FROM airline_ticket_bookings
Where ticket_status ='Confirmed'

(5) Find the number of bookings for each destination.

SELECT destination , COUNT(*) AS Number_of_bookings
FROM airline_ticket_bookings
GROUP BY destination

(6) Calculate the average ticket price for business class bookings.

SELECT AVG(price) AS average_ticket_price
FROM airline_ticket_bookings
WHERE class = 'Business'

"ADVANCE":-

(7) Find the top 3 destinations with the highest number of bookings.

SELECT destination, COUNT(*) AS Number_of_Bookings
FROM airline_ticket_bookings
GROUP BY destination
ORDER BY Number_of_Bookings DESC
LIMIT 3

(8) Calculate the total revenue generated by each payment method.

SELECT payment_method, SUM(price) AS total_revenue
FROM airline_ticket_bookings
GROUP BY payment_method


(9) Retrieve the most recent booking for each customer.

SELECT Customer_ID, Customer_Name, MAX(Booking_Date) AS Last_Booking_Date
FROM airline_ticket_bookings
GROUP BY Customer_ID, Customer_Name;

(10) Find the percentage of confirmed bookings for each class type (Economy, Business, First).

SELECT Class, 
       COUNT(*) * 100.0 / (SELECT COUNT(*) FROM airline_ticket_bookings) AS Percentage
FROM airline_ticket_bookings
WHERE Ticket_Status = 'Confirmed'
GROUP BY Class







